### ISSUE TITLE
Connected textures

### ISSUE THREAD

**Issue by travismlee** [gummy77/Corkboard#1]
Super fun mod to use so far! Would love it if there were connected textures between adjacent corkboards to make it more seamless.

**Comment by gummy77** [comment]
Yea, I did think about it, though I gave up as I didn't want to sink too much time into the project.
I might add in a later update if I have inspiration/energy.

**Comment by Fabsian10000** [comment]
hi, thought id join in on this, i saw ur mod and its perfect for what i need in my modpack, id love to help improve it! if you would like i could provide the textures needed for the implementation. i dam somewhat experienced with texture work so im sure i could help out

**Comment by gummy77** [comment]
Hi, it's less of a texturing issue and more of a programming one. Thanks for the offer though!
